# documentation: https://wger.readthedocs.io/en/latest/
# slogan: A free, open-source and cross-platform workout manager
# tags: workout, fitness, health, gym, exercises, training
# logo: svgs/wger.svg
# port: 2284

services:
  web:
    image: wger/server:latest
    depends_on:
      db:
        condition: service_healthy
      cache:
        condition: service_healthy
    environment:
      - SECRET_KEY=$SERVICE_BASE64_SECRET
      - SIGNING_KEY=$SERVICE_BASE64_SIGN
      - TIME_ZONE=${TIME_ZONE:-Europe/Berlin}
      - CSRF_TRUSTED_ORIGINS=https://${SERVICE_FQDN_NGINX},https://${SERVICE_FQDN_NGINX_2}
      - X_FORWARDED_PROTO_HEADER_SET=${X_FORWARDED_PROTO_HEADER_SET:-True}
      - MEDIA_URL=https://${SERVICE_FQDN_NGINX}/media/
      - STATIC_URL=https://${SERVICE_FQDN_NGINX}/static/
      - WGER_INSTANCE=${WGER_INSTANCE:-https://wger.de}
      - ALLOW_REGISTRATION=${ALLOW_REGISTRATION:-True}
      - ALLOW_GUEST_USERS=${ALLOW_GUEST_USERS:-True}
      - ALLOW_UPLOAD_VIDEOS=${ALLOW_UPLOAD_VIDEOS:-True}
      - MIN_ACCOUNT_AGE_TO_TRUST=${MIN_ACCOUNT_AGE_TO_TRUST:-21}
      - SYNC_EXERCISES_CELERY=${SYNC_EXERCISES_CELERY:-True}
      - SYNC_EXERCISE_IMAGES_CELERY=${SYNC_EXERCISE_IMAGES_CELERY:-True}
      - SYNC_EXERCISE_VIDEOS_CELERY=${SYNC_EXERCISE_VIDEOS:-True}
      - SYNC_INGREDIENTS_CELERY=${SYNC_INGREDIENTS_CELERY:-True}
      - DOWNLOAD_INGREDIENTS_FROM=${DOWNLOAD_INGREDIENTS_FROM:-WGER}
      - USE_CELERY=${USE_CELERY:-True}
      - CELERY_BROKER=${CELERY_BROKER:-redis://cache:6379/2}
      - CELERY_BACKEND=${CELERY_BACKEND:-redis://cache:6379/2}
      - CELERY_FLOWER_PASSWORD=$SERVICE_PASSWORD_WEB
      - DJANGO_DB_ENGINE=${DJANGO_DB_ENGINE:-django.db.backends.postgresql}
      - DJANGO_DB_DATABASE=${DJANGO_DB_DATABASE:-wger}
      - DJANGO_DB_USER=${DJANGO_DB_USER:-wger}
      - DJANGO_DB_PASSWORD=${SERVICE_PASSWORD_DB}
      - DJANGO_DB_HOST=${DJANGO_DB_HOST:-db}
      - DJANGO_DB_PORT=${DJANGO_DB_PORT:-5432}
      - DJANGO_PERFORM_MIGRATIONS=${DJANGO_PERFORM_MIGRATIONS:-True}
      - DJANGO_CACHE_BACKEND=${DJANGO_CACHE_BACKEND:-django_redis.cache.RedisCache}
      - DJANGO_CACHE_LOCATION=${DJANGO_CACHE_LOCATION:-redis://cache:6379/1}
      - DJANGO_CACHE_TIMEOUT=${DJANGO_CACHE_TIMEOUT:-1296000}
      - DJANGO_CACHE_CLIENT_CLASS=${DJANGO_CACHE_CLIENT_CLASS:-django_redis.client.DefaultClient}
      - AXES_ENABLED=${AXES_ENABLED:-True}
      - AXES_FAILURE_LIMIT=${AXES_FAILURE_LIMIT:-10}
      - AXES_COOLOFF_TIME=${AXES_COOLOFF_TIME:-30}
      - AXES_HANDLER=${AXES_HANDLER:-axes.handlers.cache.AxesCacheHandler}
      - AXES_LOCKOUT_PARAMETERS=${AXES_LOCKOUT_PARAMETERS:-ip_address}
      - AXES_IPWARE_PROXY_COUNT=${AXES_IPWARE_PROXY_COUNT:-1}
      - AXES_IPWARE_META_PRECEDENCE_ORDER=${AXES_IPWARE_META_PRECEDENCE_ORDER:-HTTP_X_FORWARDED_FOR,REMOTE_ADDR}
      - DJANGO_DEBUG=${DJANGO_DEBUG:-False}
      - WGER_USE_GUNICORN=${WGER_USE_GUNICORN:-True}
      - EXERCISE_CACHE_TTL=${EXERCISE_CACHE_TTL:-18000}
      - SITE_URL=${SITE_URL:-http://${SERVICE_FQDN_NGINX}}
      - ACCESS_TOKEN_LIFETIME=${ACCESS_TOKEN_LIFETIME:-10}
      - REFRESH_TOKEN_LIFETIME=${REFRESH_TOKEN_LIFETIME:-24}
      - USE_RECAPTCHA=${USE_RECAPTCHA:-False}
      - DJANGO_CLEAR_STATIC_FIRST=${DJANGO_CLEAR_STATIC_FIRST:-False}
      - FROM_EMAIL=${FROM_EMAIL:-'wger Workout Manager <wger@example.com>'}
      - NUMBER_OF_PROXIES=${NUMBER_OF_PROXIES:-3}
    volumes:
      - wger-static:/home/wger/static
    expose:
      - 8000
    healthcheck:
      test: wget --no-verbose --tries=1 --spider http://localhost:8000
      interval: 10s
      timeout: 5s
      start_period: 300s
      retries: 5
    restart: unless-stopped

  nginx:
    image: nginx:stable
    depends_on:
      - web
    volumes:
      - type: bind
        source: ./nginx/nginx.conf.template
        target: /etc/nginx/conf.d/default.conf
        read_only: true
        content: |
          upstream wger {
              server web:8000;
          }

            server {

            listen 80;

            location / {
            proxy_pass http://wger;
            proxy_set_header Host $host;
            proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
            proxy_set_header X-Forwarded-Proto $http_x_forwarded_proto;
            proxy_set_header X-Forwarded-Host $host:$server_port;
            proxy_redirect off;
          }

            location /static/ {
            alias /wger/static/;
          }

            location /media/ {
            alias /wger/media/;
          }

          # Increase max body size to allow for video uploads
            client_max_body_size 100M;
          }
      - wger-static:/wger/static:ro
      - wger-media:/wger/media:ro
    ports:
      - "2284:80"
    healthcheck:
      test: service nginx status
      interval: 10s
      timeout: 5s
      retries: 5
      start_period: 30s
    restart: unless-stopped

  db:
    image: postgres:15-alpine
    environment:
      - POSTGRES_USER=wger
      - POSTGRES_PASSWORD=wger
      - POSTGRES_DB=wger
    volumes:
      - wger-postgres-data:/var/lib/postgresql/data/
    expose:
      - 5432
    healthcheck:
      test: pg_isready -U wger
      interval: 10s
      timeout: 5s
      retries: 5
      start_period: 30s
    restart: unless-stopped

  cache:
    image: redis
    expose:
      - 6379
    volumes:
      - wger-redis-data:/data
    healthcheck:
      test: redis-cli ping
      interval: 10s
      timeout: 5s
      retries: 5
      start_period: 30s
    restart: unless-stopped

  celery_worker:
    image: wger/server:latest
    command: /start-worker
    environment:
      - SECRET_KEY=$SERVICE_BASE64_SECRET
      - SIGNING_KEY=$SERVICE_BASE64_SIGN
      - TIME_ZONE=${TIME_ZONE:-Europe/Berlin}
      - CSRF_TRUSTED_ORIGINS=https://${SERVICE_FQDN_NGINX},https://${SERVICE_FQDN_NGINX_2}
      - X_FORWARDED_PROTO_HEADER_SET=${X_FORWARDED_PROTO_HEADER_SET:-True}
      - MEDIA_URL=https://${SERVICE_FQDN_NGINX}/media/
      - STATIC_URL=https://${SERVICE_FQDN_NGINX}/static/
      - WGER_INSTANCE=${WGER_INSTANCE:-https://wger.de}
      - ALLOW_REGISTRATION=${ALLOW_REGISTRATION:-True}
      - ALLOW_GUEST_USERS=${ALLOW_GUEST_USERS:-True}
      - ALLOW_UPLOAD_VIDEOS=${ALLOW_UPLOAD_VIDEOS:-True}
      - MIN_ACCOUNT_AGE_TO_TRUST=${MIN_ACCOUNT_AGE_TO_TRUST:-21}
      - SYNC_EXERCISES_CELERY=${SYNC_EXERCISES_CELERY:-True}
      - SYNC_EXERCISE_IMAGES_CELERY=${SYNC_EXERCISE_IMAGES_CELERY:-True}
      - SYNC_EXERCISE_VIDEOS_CELERY=${SYNC_EXERCISE_VIDEOS:-True}
      - SYNC_INGREDIENTS_CELERY=${SYNC_INGREDIENTS_CELERY:-True}
      - DOWNLOAD_INGREDIENTS_FROM=${DOWNLOAD_INGREDIENTS_FROM:-WGER}
      - USE_CELERY=${USE_CELERY:-True}
      - CELERY_BROKER=${CELERY_BROKER:-redis://cache:6379/2}
      - CELERY_BACKEND=${CELERY_BACKEND:-redis://cache:6379/2}
      - CELERY_FLOWER_PASSWORD=$SERVICE_PASSWORD_WEB
      - DJANGO_DB_ENGINE=${DJANGO_DB_ENGINE:-django.db.backends.postgresql}
      - DJANGO_DB_DATABASE=${DJANGO_DB_DATABASE:-wger}
      - DJANGO_DB_USER=${DJANGO_DB_USER:-wger}
      - DJANGO_DB_PASSWORD=${SERVICE_PASSWORD_DB}
      - DJANGO_DB_HOST=${DJANGO_DB_HOST:-db}
      - DJANGO_DB_PORT=${DJANGO_DB_PORT:-5432}
      - DJANGO_PERFORM_MIGRATIONS=${DJANGO_PERFORM_MIGRATIONS:-True}
      - DJANGO_CACHE_BACKEND=${DJANGO_CACHE_BACKEND:-django_redis.cache.RedisCache}
      - DJANGO_CACHE_LOCATION=${DJANGO_CACHE_LOCATION:-redis://cache:6379/1}
      - DJANGO_CACHE_TIMEOUT=${DJANGO_CACHE_TIMEOUT:-1296000}
      - DJANGO_CACHE_CLIENT_CLASS=${DJANGO_CACHE_CLIENT_CLASS:-django_redis.client.DefaultClient}
      - AXES_ENABLED=${AXES_ENABLED:-True}
      - AXES_FAILURE_LIMIT=${AXES_FAILURE_LIMIT:-10}
      - AXES_COOLOFF_TIME=${AXES_COOLOFF_TIME:-30}
      - AXES_HANDLER=${AXES_HANDLER:-axes.handlers.cache.AxesCacheHandler}
      - AXES_LOCKOUT_PARAMETERS=${AXES_LOCKOUT_PARAMETERS:-ip_address}
      - AXES_IPWARE_PROXY_COUNT=${AXES_IPWARE_PROXY_COUNT:-1}
      - AXES_IPWARE_META_PRECEDENCE_ORDER=${AXES_IPWARE_META_PRECEDENCE_ORDER:-HTTP_X_FORWARDED_FOR,REMOTE_ADDR}
      - DJANGO_DEBUG=${DJANGO_DEBUG:-False}
      - WGER_USE_GUNICORN=${WGER_USE_GUNICORN:-True}
      - EXERCISE_CACHE_TTL=${EXERCISE_CACHE_TTL:-18000}
      - SITE_URL=${SITE_URL:-http://${SERVICE_FQDN_NGINX}}
      - ACCESS_TOKEN_LIFETIME=${ACCESS_TOKEN_LIFETIME:-10}
      - REFRESH_TOKEN_LIFETIME=${REFRESH_TOKEN_LIFETIME:-24}
      - USE_RECAPTCHA=${USE_RECAPTCHA:-False}
      - DJANGO_CLEAR_STATIC_FIRST=${DJANGO_CLEAR_STATIC_FIRST:-False}
      - FROM_EMAIL=${FROM_EMAIL:-'wger Workout Manager <wger@example.com>'}
      - NUMBER_OF_PROXIES=${NUMBER_OF_PROXIES:-3}
    volumes:
      - wger-media:/home/wger/media
    depends_on:
      web:
        condition: service_healthy
    healthcheck:
      test: celery -A wger inspect ping
      interval: 10s
      timeout: 5s
      retries: 5
      start_period: 30s

  celery_beat:
    image: wger/server:latest
    command: /start-beat
    environment:
      - SECRET_KEY=$SERVICE_BASE64_SECRET
      - SIGNING_KEY=$SERVICE_BASE64_SIGN
      - TIME_ZONE=${TIME_ZONE:-Europe/Berlin}
      - CSRF_TRUSTED_ORIGINS=https://${SERVICE_FQDN_NGINX},https://${SERVICE_FQDN_NGINX_2}
      - X_FORWARDED_PROTO_HEADER_SET=${X_FORWARDED_PROTO_HEADER_SET:-True}
      - MEDIA_URL=https://${SERVICE_FQDN_NGINX}/media/
      - STATIC_URL=https://${SERVICE_FQDN_NGINX}/static/
      - WGER_INSTANCE=${WGER_INSTANCE:-https://wger.de}
      - ALLOW_REGISTRATION=${ALLOW_REGISTRATION:-True}
      - ALLOW_GUEST_USERS=${ALLOW_GUEST_USERS:-True}
      - ALLOW_UPLOAD_VIDEOS=${ALLOW_UPLOAD_VIDEOS:-True}
      - MIN_ACCOUNT_AGE_TO_TRUST=${MIN_ACCOUNT_AGE_TO_TRUST:-21}
      - SYNC_EXERCISES_CELERY=${SYNC_EXERCISES_CELERY:-True}
      - SYNC_EXERCISE_IMAGES_CELERY=${SYNC_EXERCISE_IMAGES_CELERY:-True}
      - SYNC_EXERCISE_VIDEOS_CELERY=${SYNC_EXERCISE_VIDEOS:-True}
      - SYNC_INGREDIENTS_CELERY=${SYNC_INGREDIENTS_CELERY:-True}
      - DOWNLOAD_INGREDIENTS_FROM=${DOWNLOAD_INGREDIENTS_FROM:-WGER}
      - USE_CELERY=${USE_CELERY:-True}
      - CELERY_BROKER=${CELERY_BROKER:-redis://cache:6379/2}
      - CELERY_BACKEND=${CELERY_BACKEND:-redis://cache:6379/2}
      - CELERY_FLOWER_PASSWORD=$SERVICE_PASSWORD_WEB
      - DJANGO_DB_ENGINE=${DJANGO_DB_ENGINE:-django.db.backends.postgresql}
      - DJANGO_DB_DATABASE=${DJANGO_DB_DATABASE:-wger}
      - DJANGO_DB_USER=${DJANGO_DB_USER:-wger}
      - DJANGO_DB_PASSWORD=${SERVICE_PASSWORD_DB}
      - DJANGO_DB_HOST=${DJANGO_DB_HOST:-db}
      - DJANGO_DB_PORT=${DJANGO_DB_PORT:-5432}
      - DJANGO_PERFORM_MIGRATIONS=${DJANGO_PERFORM_MIGRATIONS:-True}
      - DJANGO_CACHE_BACKEND=${DJANGO_CACHE_BACKEND:-django_redis.cache.RedisCache}
      - DJANGO_CACHE_LOCATION=${DJANGO_CACHE_LOCATION:-redis://cache:6379/1}
      - DJANGO_CACHE_TIMEOUT=${DJANGO_CACHE_TIMEOUT:-1296000}
      - DJANGO_CACHE_CLIENT_CLASS=${DJANGO_CACHE_CLIENT_CLASS:-django_redis.client.DefaultClient}
      - AXES_ENABLED=${AXES_ENABLED:-True}
      - AXES_FAILURE_LIMIT=${AXES_FAILURE_LIMIT:-10}
      - AXES_COOLOFF_TIME=${AXES_COOLOFF_TIME:-30}
      - AXES_HANDLER=${AXES_HANDLER:-axes.handlers.cache.AxesCacheHandler}
      - AXES_LOCKOUT_PARAMETERS=${AXES_LOCKOUT_PARAMETERS:-ip_address}
      - AXES_IPWARE_PROXY_COUNT=${AXES_IPWARE_PROXY_COUNT:-1}
      - AXES_IPWARE_META_PRECEDENCE_ORDER=${AXES_IPWARE_META_PRECEDENCE_ORDER:-HTTP_X_FORWARDED_FOR,REMOTE_ADDR}
      - DJANGO_DEBUG=${DJANGO_DEBUG:-False}
      - WGER_USE_GUNICORN=${WGER_USE_GUNICORN:-True}
      - EXERCISE_CACHE_TTL=${EXERCISE_CACHE_TTL:-18000}
      - SITE_URL=${SITE_URL:-http://${SERVICE_FQDN_NGINX}}
      - ACCESS_TOKEN_LIFETIME=${ACCESS_TOKEN_LIFETIME:-10}
      - REFRESH_TOKEN_LIFETIME=${REFRESH_TOKEN_LIFETIME:-24}
      - USE_RECAPTCHA=${USE_RECAPTCHA:-False}
      - DJANGO_CLEAR_STATIC_FIRST=${DJANGO_CLEAR_STATIC_FIRST:-False}
      - FROM_EMAIL=${FROM_EMAIL:-'wger Workout Manager <wger@example.com>'}
      - NUMBER_OF_PROXIES=${NUMBER_OF_PROXIES:-3}
    volumes:
      - wger-celery-beat:/home/wger/beat/
    depends_on:
      celery_worker:
        condition: service_healthy

volumes:
  wger-postgres-data:
  wger-celery-beat:
  wger-static:
  wger-media:
  wger-redis-data:

networks:
  default:
    name: wger_network
